Adição de validação do campo do formulário antes da inserçao do valor…
paulo-raoni/CRUD-JavaScript-Puro pull request #1
Opened 2022-12-13 17:00 UTC by P-a-u-l-o

Opa professor tudo bem, então acompanhando suas aulas no YT decidi utilizar o conhecimento adquirido para realizar uma pequena alteração de melhoria no código demonstrado na aula JavaScript Básico 29 - CRUD em JavaScript Manipulando o DOM.
Realizei a inserção de uma pequena validação do campo "Linguagem" presente no simples formulário com o JavaScript é claro, sinto-me muito feliz em poder fazer parte deste pequeno projeto e agradeço muito por  ter a paciência em compartilhar o conhecimento com muitos outros quem tem um interesse em comum que é o aprendizado de desenvolvimento Web, forte abraço e espero que este Pull Request possa ser aprovado ☺.

2022-12-15 16:53 UTC, paulo-raoni commented
Oi xará, realmente essa parte do código estava sem validação. Obrigado por ajudar. No entanto, eu reparei algumas coisas no seu código que seriam pontos de melhoria, e outros que seriam boas práticas mesmo. 

Vou deixar comentando, e quando você resolver esses comentários, caso eu demore a responder por aqui, você pode me chamar pelo instagram que está bem fácil de achar lá no canal.

2022-12-15 17:19 UTC, paulo-raoni requested changes
Oi xará, mais uma vez obrigado por contribuir com esse simples projeto demonstrativo. Fico muito agradecido, e feliz por ver alguém interessado assim. Parabéns pela iniciativa.

Deixei alguns comentários no código, afim de melhorar o desempenho e leitura do mesmo. Assim que você resolver, é só me dar um toque. Um abraço e bons estudos.

2022-12-15 17:19 UTC, paulo-raoni commented on index.html
> -    <head>
Para evitar essa discrepância de diferenças no commit, peço que remova os espaços a mais nas linhas de código que provavelmente, com o auxílio de alguma extensão, seu editor lançou.

2022-12-15 17:19 UTC, paulo-raoni commented on index.html
> +			<div>
Mais uma vez, uma longa diferença nos espaçamentos. Caso tenha dificuldades em resolver isso, tente usar o git mesmo, voltando um passo atrás, mudando só as alterações depois fazendo um novo commit. Você pode usar o comando cherry pick pra pegar só as partes importantes, e fazer um novo commit.  Formas de resolver isso tem aos montes. Só dar uma pesquisada.

2022-12-15 17:19 UTC, paulo-raoni commented on script.js
> +	if (valor == "") {
Uma boa prática é fazer as validações sempre antes de realizar qualquer ação, isso se chama "early return". Com isso, a gente evita que o código processe tudo de forma desnecessária. 

Sobre esse código, tenho alguns comentários para você alterar:
1- Reposicionar esse mais acima, sendo mais específico, na linha 66. Pois aí vamos nos certificar de fazer o "early return". E quando fizer isso, remover o else, já que não será mais necessário, dessa forma a gente reduz complexidade de leitura do código.

2- Em vez de colocar `if(valor == "")`, você poderia usar três iguais em vez de dois. Só que eu ainda tenho uma forma ainda mais reduzida e mais legível, que seria simplesmente uma negação da constante valor, dessa forma `if(!valor)`. Lembra da aula sobre booleanos e estruturas condicionais?

3- Usar a função alert() não é errado, porém, como isso é uma validação de campo de formulário, eu usaria algo mais "user friendly", como uma tag <span> com letras vermelhas logo abaixo do campo <input> adicionado essa mesma mensagem. 
Dá menos "medo" no usuário ter mensagens sutis em vez de blocos pipocando na tela. Tente sempre se colocar no lugar do usuário. O que fica menos agressivo, uma janela estourando na cara dele, ou uma mensagem discreta abaixo do campo onde ela está digitando?

2022-12-18 19:51 UTC, P-a-u-l-o commented
Opa boa tarde mais uma vez professor, tentei realizar as solicitações pedidas e acabei adicionando mais algumas linhas de alterações no código, porém realizei os comentários necessários para facilitar o entendimento, realizei a alteração que me solicitou só não consegui fazer o recuo das indentações não sei o que acontece dentro da meu VSCODE o código está correto e com indentação normal, porém, todas as vezes que tentei commitar, ele ficou com esse espaçamentos irregulares, eu desabilitei as extensões de correção de código 'Beutify, EsLint, Prettier' não adiantou, exclui os arquivos e tentei commitar novamente mas não resolveu poderia por favor me dar um direcionamento se possível, a questão da verificação do campo foi resolvida espero que esteja correta, desde já fico no aguardo e agradeço toda sua atenção.

2022-12-22 02:51 UTC, paulo-raoni requested changes
Fiz mais alguns comentários. Você não precisa ter duas funções para renderizar e desfazer a renderização, você pode fazer tudo em uma só, como uma função alteranadora. Caso tenha valor não renderiza, caso não tenha renderiza.

2022-12-22 02:51 UTC, paulo-raoni commented on script.js
> +function removeValidaInput() {
Isso aqui poderia ser um método só, tipo renderizaMensagemErro(), que vai ser de acordo com a situação do valor do campo, se não tiver nada, renderiza com a mensagem, se tiver valor, renderiza sem nada.

E você vai precisar passar o valor no parâmetro, pra verificar ele, essa forma que você está fazendo, além de ser redundante, pode gerar mais confusão no código.

2022-12-22 02:51 UTC, paulo-raoni commented on script.js
> +function validaInput() {
Isso aqui poderia ser um método só, tipo renderizaMensagemErro(), que vai ser de acordo com a situação do valor do campo, se não tiver nada, renderiza com a mensagem, se tiver valor, renderiza sem nada.

E você vai precisar passar o valor no parâmetro, pra verificar ele, essa forma que você está fazendo, além de ser redundante, pode gerar mais confusão no código.

2022-12-22 02:51 UTC, paulo-raoni commented on script.js
> +	if (!valor) {
Em vez de ter esse if aqui, ele pode ser dentro do método renderizaMensagemErro(). Isso vai deixar o código mais limpo, e vai reduzir a complexidade.

2022-12-22 02:51 UTC, paulo-raoni commented on script.js
> +		removeValidaErro();
Com um método único para validaInput e removeValidaErro, você pode fazer tudo em uma chamada só. Então essa chamada aqui também não vai existir mais.

2022-12-22 02:53 UTC, paulo-raoni commented
> Opa boa tarde mais uma vez professor, tentei realizar as solicitações pedidas e acabei adicionando mais algumas linhas de alterações no código, porém realizei os comentários necessários para facilitar o entendimento, realizei a alteração que me solicitou só não consegui fazer o recuo das indentações não sei o que acontece dentro da meu VSCODE o código está correto e com indentação normal, porém, todas as vezes que tentei commitar, ele ficou com esse espaçamentos irregulares, eu desabilitei as extensões de correção de código 'Beutify, EsLint, Prettier' não adiantou, exclui os arquivos e tentei commitar novamente mas não resolveu poderia por favor me dar um direcionamento se possível, a questão da verificação do campo foi resolvida espero que esteja correta, desde já fico no aguardo e agradeço toda sua atenção.

Sobre o espaçamento, deixa assim por enquanto. Era só pra você se atentar, mas deve ser algum bug. Como não está interferindo na funcionalidade, vamos deixar assim. Só resolve os outros comentários pra mim, por favor. Assim que você resolver eu faço o merge das alterações.

2022-12-22 21:18 UTC, P-a-u-l-o commented on script.js
> +function removeValidaInput() {
Ok!

2022-12-22 21:18 UTC, P-a-u-l-o commented on script.js
> +function validaInput() {
Ok!

2022-12-22 22:23 UTC, P-a-u-l-o commented
Boa noite novamente professor, obrigado pelas ressalvas que tem feito em meus códigos.
Refatorei o código conforme solicitado, removi as funções validaInput() e removeValidaInput() e criei uma única função conforme solicitou renderizaMensagemErro() analisei as partes supracitadas e tentei deixar o mais próximo do solicitado possível conforme o conhecimento que vim adquirindo, espero que esteja de acordo, caso ainda existam ressalvas por favor não deixe de informá-las ficarei muito agradecido pois tem me ajudado bastante a melhorar e entender a lógica por trás do JavaScript, mais uma vez agradeço a paciência e todos os retornos que tem me fornecido neste pequeno projeto, abraço.

2022-12-24 03:09 UTC, paulo-raoni commented
> Boa noite novamente professor, obrigado pelas ressalvas que tem feito em meus códigos. Refatorei o código conforme solicitado, removi as funções validaInput() e removeValidaInput() e criei uma única função conforme solicitou renderizaMensagemErro() analisei as partes supracitadas e tentei deixar o mais próximo do solicitado possível conforme o conhecimento que vim adquirindo, espero que esteja de acordo, caso ainda existam ressalvas por favor não deixe de informá-las ficarei muito agradecido pois tem me ajudado bastante a melhorar e entender a lógica por trás do JavaScript, mais uma vez agradeço a paciência e todos os retornos que tem me fornecido neste pequeno projeto, abraço.

Que bom que você está aprendendo. Dá uma olhada que tem ainda mais algumas coisas que ficaram faltando.

2022-12-24 03:10 UTC, paulo-raoni commented
> Boa noite novamente professor, obrigado pelas ressalvas que tem feito em meus códigos. Refatorei o código conforme solicitado, removi as funções validaInput() e removeValidaInput() e criei uma única função conforme solicitou renderizaMensagemErro() analisei as partes supracitadas e tentei deixar o mais próximo do solicitado possível conforme o conhecimento que vim adquirindo, espero que esteja de acordo, caso ainda existam ressalvas por favor não deixe de informá-las ficarei muito agradecido pois tem me ajudado bastante a melhorar e entender a lógica por trás do JavaScript, mais uma vez agradeço a paciência e todos os retornos que tem me fornecido neste pequeno projeto, abraço.

Uma outra coisa, quando você resolver um comentário, você precisa me avisar no comentário, pra eu marcar como "resolved".

2023-08-04 17:24 UTC, closed without merging